 .github/ISSUE_TEMPLATE/bug_report.yml
name:  Reporte de Error
description: Reportar un error, inconsistencia o contenido incorrecto en los challenges
title: "BUG"
labels: "bug", "needs-triage"
assignees:
  - carmen-delia-manzano

body:
  - type: markdown
    attributes:
      value: |
        Gracias por tomarte el tiempo de reportar este error. Tu contribuci贸n ayuda a mejorar la calidad del repositorio.

  - type: dropdown
    id: challenge
    attributes:
      label: Challenge Afectado
      description: 驴En qu茅 challenge encontraste el error?
      options:
        - Challenge #2 - Optimizaci贸n de Urgencias Hospitalarias
        - Challenge #3 - Planificaci贸n Estrat茅gica de Herencias
        - Challenge #4 - Transformaci贸n de Sistema Educativo Universitario
        - Documentaci贸n general (README, CONTRIBUTING, etc.)
        - M煤ltiples challenges
        - Otro
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Ubicaci贸n Exacta
      description: "Archivo y secci贸n donde est谩 el error"
      placeholder: "Ej: challenge2-urgencias-hospitalarias.md, Secci贸n: An谩lisis de Riesgos, l铆neas ~250-280"
    validations:
      required: true

  - type: dropdown
    id: error-type
    attributes:
      label: Tipo de Error
      description: Categoriza el tipo de error encontrado
      multiple: false
      options:
        - Error factual (dato incorrecto)
        - Error metodol贸gico (aplicaci贸n incorrecta de framework)
        - Error de c谩lculo (n煤meros/ROI/proyecciones)
        - Inconsistencia interna (contradicci贸n en el documento)
        - Error tipogr谩fico/gramatical grave
        - Enlace roto o recurso no disponible
        - Disclaimer faltante o incompleto
        - Otro
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Contenido Actual (Incorrecto)
      description: Copia el texto exacto que contiene el error
      placeholder: |
        Ejemplo:
        "La tasa de deserci贸n objetivo es del 15%"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: expected-content
    attributes:
      label: Contenido Esperado (Correcci贸n Propuesta)
      description: 驴C贸mo deber铆a ser el contenido correcto?
      placeholder: |
        Ejemplo:
        "La tasa de deserci贸n objetivo es <20% (benchmark internacional)"
      render: markdown
    validations:
      required: true

  - type: textarea
    id: justification
    attributes:
      label: Justificaci贸n del Error
      description: Explica por qu茅 esto es incorrecto y proporciona fuentes si es posible
      placeholder: |
        Seg煤n el estudio de XYZ (2024), el benchmark internacional para...
        Referencias:
        - [Fuente 1]
        - [Fuente 2]
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severidad del Error
      description: 驴Qu茅 tan cr铆tico es este error?
      options:
        -  Cr铆tico - Error grave que puede causar da帽o si se aplica
        -  Alto - Error significativo que afecta credibilidad
        -  Medio - Error moderado, afecta precisi贸n
        -  Bajo - Error menor, no afecta comprensi贸n general
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Justificaci贸n de Severidad
      description: 驴Por qu茅 consideras este nivel de impacto?
      placeholder: Este error es cr铆tico porque...

  - type: textarea
    id: additional
    attributes:
      label: Informaci贸n Adicional
      description: Cualquier otro contexto relevante (capturas, enlaces, etc.)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Confirma antes de enviar
      options:
        - label: He buscado si este error ya fue reportado
          required: true
        - label: He proporcionado ubicaci贸n exacta del error
          required: true
        - label: He incluido justificaci贸n fundamentada
          required: true
        - label: He le铆do la [Gu铆a de Contribuci贸n](https://github.com/usuario/repo/blob/main/CONTRIBUTING.md)
          required: true
