📄 .github/config.yml (Configuración de Templates)
blank_issues_enabled: false
contact_links:
  - name: 💬 Discusiones Generales
    url: https://github.com/usuario/clara-4-challenges/discussions
    about: Para conversaciones abiertas, ideas, y feedback general
  - name: 📧 Contacto Directo
    url: mailto: controlsafemail.365@keemail.me
    about: Para consultas privadas o propuestas comerciales
  - name: 📚 Documentación
    url: https://github.com/usuario/clara-4-challenges/blob/main/README.md
    about: Lee la documentación completa del proyecto
