name: "🚀 Propuesta de Nuevo Challenge"
description: "Sugerir un nuevo challenge para el repositorio"
title: "[NEW CHALLENGE] "
labels: ["enhancement", "new-challenge"]
assignees:
  - carmen-delia-manzano

body:
  - type: markdown
    attributes:
      value: |
        ¡Gracias por proponer un nuevo challenge! Estas propuestas enriquecen el repositorio y benefician a toda la comunidad profesional.

  - type: input
    id: title
    attributes:
      label: "Título del Challenge"
      description: "Nombre descriptivo y profesional"
      placeholder: "Ej: Optimización de Cadena de Suministro en PYME Manufacturera"
    validations:
      required: true

  - type: input
    id: sector
    attributes:
      label: "Sector/Industria"
      description: "Área de aplicación principal"
      placeholder: "Ej: Manufactura, Finanzas, Tecnología, Gobierno, ONGs"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: "Nivel de Complejidad Estimado"
      options:
        - label: "⭐⭐⭐ (Medio)"
        - label: "⭐⭐⭐⭐ (Alto)"
        - label: "⭐⭐⭐⭐⭐ (Muy Alto)"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Contexto del Escenario"
      description: "Descripción general del problema o situación a analizar"
      placeholder: |
        Ejemplo:
        PYME manufacturera con 250 empleados enfrenta problemas de eficiencia en su cadena de suministro:
        - Retrasos en entregas (30% pedidos con delay)
        - Exceso de inventario ($2M inmovilizado)
        - Coordinación deficiente con proveedores
        - Falta de visibilidad en tiempo real
    validations:
      required: true

  - type: textarea
    id: organization
    attributes:
      label: "Organización Tipo (Características)"
      description: "Tamaño, facturación, estructura, ubicación (si es relevante)"
      placeholder: |
        - Tamaño: 250 empleados
        - Facturación: $30M/año
        - Estructura: Familiar, 2da generación
        - Ubicación: Región industrializada
        - Mercado: B2B, 80% nacional, 20% exportación

  - type: textarea
    id: problem
    attributes:
      label: "Problemática Principal"
      description: "Descripción detallada del desafío estratégico/operativo"
      placeholder: |
        **Síntomas del problema:**
        1. Tiempo promedio de entrega: 45 días (objetivo: 30 días)
        2. Tasa de cumplimiento: 70% (benchmark: >95%)
        3. Costo de almacenamiento: 15% del COGS (objetivo: <8%)
        4. Stock-outs: 12 eventos/año con pérdida promedio $50K c/u
        
        **Datos críticos:**
        - SKUs gestionados: 1,200
        - Proveedores activos: 85 (60% concentración en top 10)
        - Sistemas: ERP básico sin módulo SCM avanzado
        - Equipo logística: 8 personas, sin formación especializada
    validations:
      required: true

  - type: checkboxes
    id: capabilities
    attributes:
      label: "Capacidades de Clara 4.0 a Demostrar"
      description: "Marca todas las que apliquen"
      options:
        - label: "Diagnóstico de sistemas complejos"
        - label: "Optimización de procesos"
        - label: "Gestión del cambio organizacional"
        - label: "Análisis de riesgos multidimensional"
        - label: "Planificación estratégica"
        - label: "Análisis de viabilidad (financiera/operativa)"
        - label: "Benchmarking sectorial"
        - label: "Diseño de KPIs y dashboards"
        - label: "Selección y evaluación de tecnología"
        - label: "Gestión de stakeholders"

  - type: textarea
    id: methodologies
    attributes:
      label: "Metodologías Sugeridas"
      description: "Frameworks o herramientas que se aplicarían"
      placeholder: |
        - Lean Supply Chain
        - Theory of Constraints (TOC)
        - SCOR Model (Supply Chain Operations Reference)
        - ABC/XYZ Analysis
        - Vendor Managed Inventory (VMI)
        - ISO 28000 (Supply Chain Security)
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: "Entregables Esperados"
      description: "¿Qué generaría Clara 4.0 en este challenge?"
      placeholder: |
        1. Diagnóstico situacional con análisis de brechas
        2. Mapeo de flujos actuales (VSM - Value Stream Mapping)
        3. Identificación de cuellos de botella y desperdicios
        4. Plan estratégico de optimización en 3 fases
        5. Análisis make-or-buy de tecnología SCM
        6. Sistema de KPIs operativos (OTIF, Inventory Turnover, etc.)
        7. Roadmap de implementación (12 meses)
        8. Análisis costo-beneficio y ROI proyectado
    validations:
      required: true

  - type: textarea
    id: results
    attributes:
      label: "Resultados/Impacto Proyectado"
      description: "Mejoras cuantificables esperadas"
      placeholder: |
        - Reducción de tiempo de entrega: de 45 a 30 días (-33%)
        - Mejora en tasa de cumplimiento: de 70% a >95%
        - Reducción de inventario: de $2M a $1.2M (-40%)
        - Reducción de stock-outs: de 12 a <3 eventos/año
        - ROI esperado: 250% en 18 meses

  - type: textarea
    id: justification
    attributes:
      label: "Justificación de Relevancia"
      description: "¿Por qué este challenge es valioso para la comunidad?"
      placeholder: |
        - Alta aplicabilidad: 40% de PYMEs tienen problemas similares
        - Sector clave: Manufactura representa 18% PIB en región
        - Demanda profesional: Supply Chain es top 5 roles en LinkedIn
        - Gap educativo: Pocos casos prácticos disponibles en español
        - Complementariedad: No existe challenge similar en repositorio
    validations:
      required: true

  - type: checkboxes
    id: audience
    attributes:
      label: "Audiencia Objetivo"
      description: "¿Quiénes se beneficiarían de este challenge?"
      options:
        - label: "Consultores estratégicos"
        - label: "Gerentes de operaciones / Supply Chain"
        - label: "Directores de transformación"
        - label: "Académicos / Investigadores"
        - label: "Estudiantes de MBA / Posgrado"
        - label: "Emprendedores / Fundadores"
        - label: "Otro (especificar abajo)"

  - type: textarea
    id: references
    attributes:
      label: "Referencias y Benchmarks"
      description: "Casos reales, papers, o empresas líderes en este tema"
      placeholder: |
        **Casos similares:**
        - Toyota Production System (TPS)
        - Amazon Supply Chain optimization (caso HBS)
        - Zara: Fast Fashion Supply Chain (caso IESE)
        
        **Referencias bibliográficas:**
        - Chopra, S. & Meindl, P. (2023). Supply Chain Management (7th ed.)
        - Goldratt, E. (1984). The Goal: A Process of Ongoing Improvement
        
        **Benchmarks:**
        - Apple, Dell, Walmart (supply chain excellence)

  - type: dropdown
    id: sensitivity
    attributes:
      label: "Sensibilidad Legal/Ética"
      description: "¿Qué nivel de disclaimers requiere?"
      options:
        - label: "Bajo - Tema general sin implicaciones legales complejas"
        - label: "Medio - Requiere disclaimers estándar"
        - label: "Alto - Requiere disclaimers robustos y validación especializada"

  - type: textarea
    id: disclaimers
    attributes:
      label: "Disclaimers Necesarios"
      description: "¿Qué advertencias deben incluirse?"
      placeholder: |
        "Este análisis no sustituye asesoría de consultores especializados en 
        Supply Chain Management. Toda implementación debe considerar contexto 
        específico, regulaciones locales y capacidades organizacionales."

  - type: dropdown
    id: contribution
    attributes:
      label: "Nivel de Contribución Ofrecida"
      description: "¿Cómo te gustaría participar?"
      options:
        - label: "Puedo co-crear el challenge completo (40+ horas)"
        - label: "Puedo proporcionar contexto y revisión (10-15 horas)"
        - label: "Puedo validar la propuesta final (5 horas)"
        - label: "Solo quiero sugerir la idea"
    validations:
      required: true

  - type: textarea
    id: expertise
    attributes:
      label: "Tu Experiencia en el Tema"
      description:
